### PR TITLE
Change mod name when installation fails

### LINKED ISSUE #1334: Cancelling mod installation leaves failed mod entry in LoadoutGrid
image

If user cancelled the installation explicitly then it should not leave the entry.

### PR DESCRIPTION
**Pull request by erri120**
Resolves #1334.

### CODE REVIEW

File: src/NexusMods.DataModel/ArchiveInstaller.cs [hunk 1]
```diff
@@ -218,6 +214,7 @@ private async Task SetStatus(ModId modId, ModStatus status)
         _logger.LogInformation("Setting status of ModId:{ModId}({Name}) to {Status}", modId, mod.Name, status);
         
         using var tx = _conn.BeginTransaction();
+        tx.Add(modId.Value, Mod.Name, $"Installation failed: {mod.Name}");
```
Comment (Al12rs) [inline src/NexusMods.DataModel/ArchiveInstaller.cs:217]: This method was meant to support setting any status, not just failed status.
Either change the method to be SetFailedStatus, or check if status==ModStatus.Failed before replacing the name

**Review by Al12rs — CHANGES_REQUESTED** [review]

File: src/NexusMods.DataModel/ArchiveInstaller.cs [hunk 2]
```diff
@@ -54,20 +54,18 @@ public async Task<ModId[]> AddMods(LoadoutId loadoutId, DownloadAnalysis.Model d
...
         var useCustomInstaller = installer != null;
         var loadout = _conn.Db.Get<Loadout.Model>(loadoutId.Value);
-        
+
+        var archiveName = download.TryGet(FilePathMetadata.OriginalName, out var originalName) ? originalName.ToString() : null;
+
         var modName = defaultModName ?? (download.Contains(DownloadAnalysis.SuggestedName)
             ? download.SuggestedName
-            : "<unknown>");
+            : archiveName ?? "<unknown>");
```
Comment (Al12rs) [inline src/NexusMods.DataModel/ArchiveInstaller.cs:62]: Do the same thing for SuggestedName to make the code a bit cleaner

**Review by Al12rs — APPROVED** [review]
