### PR TITLE
Regression fixes and Mod Library improvements

### LINKED ISSUE #1299: Advanced Installer window is missing chrome and no longer has rounded borders
image

Should have a chrome titlebar and rounded borders

### LINKED ISSUE #1300: Mods installed with Advanced Installer have "<unknown>" name
image

Should use the archive name instead

### LINKED ISSUE #1310: Download throughput value is incorrect
I'm capped at 18MB/s and the SpineDownloadButton is showing much higher than that.

This happens when downloading multiple files, even one after another. It seems something isn't being reset after a download is paused/ cancelled or completed, and the new throughputs are added on top.

image

### LINKED ISSUE #1321: Regression: MyGames page should only show one widget for all loadouts of the same game install
In the image below there should only be one GameWidget instead of two.
image

Regression of #1302

### LINKED ISSUE #1327: Advanced Installer isn't being used as a fallback for installing mods (Stardew)
Advanced installer should be used as the fallback in case a download or archive isn't supported by any of the game installers.

This doesn't currently happen for Stardew when pressing the Install Mod button or when installing from Download Library view.

### PR DESCRIPTION
**Pull request by Al12rs**
- fixes #1300
- fixes #1310 
- fixes #1321 
- fixes #1299 
- fixes #1327
- Fixed exception in loadoutGrid Installed date column, value update was not happening on UI thread.
- Ticks a couple of items of #1284
    - Make list update in realtime
    - Show "-" for invalid dates
    - Show dates in humanized format (e.g. 2 minutes ago)

### CODE REVIEW

File: src/NexusMods.DataModel/ArchiveInstaller.cs [hunk 1]
```diff
@@ -50,14 +51,18 @@ public async Task<ModId[]> AddMods(LoadoutId loadoutId, DownloadAnalysis.Model d
...
-        {
-            archiveName = download.Get(DownloadAnalysis.SuggestedName);
-        }
-        
-        string modName = defaultModName ?? archiveName;
+        var modName = defaultModName ?? (download.Contains(DownloadAnalysis.SuggestedName)
+            ? download.SuggestedName
+            : "<unknown>");
 
+        var dlTx = _conn.BeginTransaction();
```
Comment (erri120) [inline src/NexusMods.DataModel/ArchiveInstaller.cs:58]: This should be disposed.

**Review by erri120 — CHANGES_REQUESTED** [review]
