### PR TITLE
Fixed: Building NMA with System Extractor

### LINKED ISSUE #1836: Tests fail when using `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR`
# Bug Report

## Summary

Tests complain they cannot find the file '/build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz'.

## Steps to reproduce

Run the tests on a build built with `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR`.

More specifically:
- install `nix`
- checkout https://github.com/NixOS/nixpkgs/pull/331150
- edit `pkgs/by-name/ne/nexusmods-app/package.nix` to remove the symlink in `postPatch`
- run `nix-build -A nexusmods-app
- run the provided `nix log` command and search for `Failed`
  - e.g. `nix log /nix/store/f97pyrppffpc96wzmx9klqlh2k0z6hm0-nexusmods-app-0.5.3.drv`
  - `/Failed` (search forward for the regex "Failed")
  - `N` (jump to next match)

## What is the expected behaviour?

I expected 7zz to be found on the PATH.

If the PATH is being searched, I'd expect that to show up in the error message.

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_

```
[xUnit.net 00:00:00.63]         System.ComponentModel.Win32Exception (2): Failed to start a process with file path '/build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz'. Target file or working directory doesn't exist, or the provided credentials are invalid. ---> System.ComponentMo>
[xUnit.net 00:00:00.63]            at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTermin>
[xUnit.net 00:00:00.63]            at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[xUnit.net 00:00:00.63]            at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56
[xUnit.net 00:00:00.63]            at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
[xUnit.net 00:00:00.63]            at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
[xUnit.net 00:00:00.63]            at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken) in /_/CliWrap/Command.Execution.cs:line 326
[xUnit.net 00:00:00.63]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync_Impl(IStreamFactory sFn, AbsolutePath destination, CancellationToken token, IActivitySource`1 activity) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 147
[xUnit.net 00:00:00.63]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync_Impl(IStreamFactory sFn, AbsolutePath destination, CancellationToken token, IActivitySource`1 activity) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 188
[xUnit.net 00:00:00.63]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath destination, CancellationToken token) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 69
[xUnit.net 00:00:00.63]            at NexusMods.FileExtractor.FileExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath dest, CancellationToken token) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/FileExtractor.cs:line 68
[xUnit.net 00:00:00.65]     NexusMods.CLI.Tests.VerbTests.ModManagementVerbs.CanCreateAndManageLists [FAIL]
[xUnit.net 00:00:00.65]       NexusMods.FileExtractor.FileExtractionException : No Extractors found for file /build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0/Resources/StubbedGameState.zip
[xUnit.net 00:00:00.65]       Stack Trace:
[xUnit.net 00:00:00.65]         /build/source/src/ArchiveManagement/NexusMods.FileExtractor/FileExtractor.cs(77,0): at NexusMods.FileExtractor.FileExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath dest, CancellationToken token)
[xUnit.net 00:00:00.65]         /build/source/src/ArchiveManagement/NexusMods.FileExtractor/FileExtractor.cs(51,0): at NexusMods.FileExtractor.FileExtractor.ExtractAllAsync(AbsolutePath path, AbsolutePath dest, CancellationToken token)
[xUnit.net 00:00:00.65]         /build/source/tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs(111,0): at NexusMods.StandardGameLocators.TestHelpers.StubbedGames.StubbedGame.AddTestFiles(TemporaryPath path, IServiceProvider provider)
[xUnit.net 00:00:00.65]         /build/source/tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs(101,0): at NexusMods.StandardGameLocators.TestHelpers.StubbedGames.StubbedGame.Create(IServiceProvider provider)
[xUnit.net 00:00:00.65]         /build/source/tests/NexusMods.CLI.Tests/VerbTests/AVerbTest.cs(93,0): at NexusMods.CLI.Tests.VerbTests.AVerbTest.CreateInstall()
[xUnit.net 00:00:00.65]         /build/source/tests/NexusMods.CLI.Tests/VerbTests/ModManagementVerbs.cs(14,0): at NexusMods.CLI.Tests.VerbTests.ModManagementVerbs.CanCreateAndManageLists()
[xUnit.net 00:00:00.65]       Output:
[xUnit.net 00:00:00.65]         [2024-07-31 16:18:20Z] dbug: NexusMods.FileExtractor.Extractors.SevenZipExtractor[0]
[xUnit.net 00:00:00.65]               Extracting StubbedGameState.zip
[xUnit.net 00:00:00.65]         [2024-07-31 16:18:20Z] dbug: NexusMods.FileExtractor.Extractors.SevenZipExtractor[0]
[xUnit.net 00:00:00.65]               Cleaning up after extraction
[xUnit.net 00:00:00.65]         [2024-07-31 16:18:20Z] fail: NexusMods.FileExtractor.FileExtractor[0]
[xUnit.net 00:00:00.65]               While extracting via NexusMods.FileExtractor.Extractors.SevenZipExtractor
[xUnit.net 00:00:00.65]         System.ComponentModel.Win32Exception (0x80004005): Failed to start a process with file path '/build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz'. Target file or working directory doesn't exist, or the provided credentials are invalid.
[xUnit.net 00:00:00.65]          ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz' with working directory '/build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0'. No such file or direc>
[xUnit.net 00:00:00.65]            at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTermin>
[xUnit.net 00:00:00.65]            at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[xUnit.net 00:00:00.65]            at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56
[xUnit.net 00:00:00.65]            at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
[xUnit.net 00:00:00.65]            at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
[xUnit.net 00:00:00.65]            at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken) in /_/CliWrap/Command.Execution.cs:line 326
[xUnit.net 00:00:00.65]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync_Impl(IStreamFactory sFn, AbsolutePath destination, CancellationToken token, IActivitySource`1 activity) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 147
[xUnit.net 00:00:00.65]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync_Impl(IStreamFactory sFn, AbsolutePath destination, CancellationToken token, IActivitySource`1 activity) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 188
[xUnit.net 00:00:00.65]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath destination, CancellationToken token) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 69
[xUnit.net 00:00:00.65]            at NexusMods.FileExtractor.FileExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath dest, CancellationToken token) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/FileExtractor.cs:line 68
  Failed NexusMods.CLI.Tests.VerbTests.ExtractArchive.CanExtractArchive [85 ms]
  Error Message:
   NexusMods.FileExtractor.FileExtractionException : No Extractors found for file /build/source/tests/NexusMods.CLI.Tests/bin/Release/net8.0/Resources/data_7zip_lzma2.7z
```

Building on this nixpkgs PR https://github.com/NixOS/nixpkgs/pull/331150 so there may be other contributing factors. E.g. I'm not 100% sure that PATH is being set correctly when running the tests.

### PR DESCRIPTION
**Pull request by Sewer56**
CC @mattsturgeon

I got some time to kill end of sprint.

This fixes the behaviour of `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR` to correctly function.
I can verify the following:

1. No `7zz` in output directory
2. System extractor is being used (easy to verify by just uninstalling it).

In addition, I have altered the code to also account for system binaries possibly being called `7z` and `7zzs`.
(Note: On my Arch system, the AUR package renames it to `7z` from `7zz` in original download)

The code does a lookup of `$PATH`, and determines the appropriate binary based on whatever it can find first.

fixes #1836

### CODE REVIEW

**Comment by Sewer56** [comment]
With respects to building, you can't modify `DefineConstants` if it's specifically set in the CLI via `-p:DefineConstants="..."`.
This seems to have been tripping me up too. So we can't do an alias by appending `DefineConstants` in the `.csproj` or `.targets` file. Instead I alias by checking both define names; it's shorter in terms of line count either way.

File: src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs [hunk 1]
```diff
@@ -221,9 +228,24 @@ private static string GetExtractorExecutable(IFileSystem fileSystem)
...
+#if NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR || USE_SYSTEM_EXTRACTOR
         true;
 #else
         false;
 #endif
+    
+    private static string FindSystem7zOnLinux()
+    {
+        string[] potentialBinaryNames = ["7z", "7zz", "7zzs"];
+        var pathDirectories = Environment.GetEnvironmentVariable("PATH")!.Split(':');
```
Comment (MattSturgeon) [inline src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:240]: I was concerned at first that this could run into edge cases, but the POSIX spec specifically says directories included in PATH cannot contain the delimitator `:`.

In other words there's no escape sequences for `:` in PATH paths, so this simple implementation is the correct one.

File: src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets [hunk 2]
```diff
@@ -13,12 +13,8 @@
     <_NativeRuntime Condition=" '$(_NativeRuntime)' == '' And '$(_IsWindows)' == 'true' And ('$(Prefer32Bit)' == 'true' Or '$(PlatformTarget)' == 'x86')">win-x86</_NativeRuntime>
     <_NativeRuntime Condition=" '$(_NativeRuntime)' == '' And '$(_IsWindows)' == 'true' And ('$(Prefer32Bit)' == 'false' Or '$(PlatformTarget)' == 'x64')">win-x64</_NativeRuntime>
 
-      <_UseSystemExtractor Condition="'$(NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR)' == '1'">true</_UseSystemExtractor>
+    <_UseSystemExtractor Condition="$([System.String]::new('$(DefineConstants)').Contains('USE_SYSTEM_EXTRACTOR')) or $([System.String]::new('$(DefineConstants)').Contains('NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR'))">true</_UseSystemExtractor>
   </PropertyGroup>
-    
-    <PropertyGroup Condition="'$(_UseSystemExtractor)' == 'true'">
-        <DefineConstants>USE_SYSTEM_EXTRACTOR</DefineConstants>
-    </PropertyGroup>
```
Comment (erri120) [inline src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets:18]: The property can be removed if it's not used.

File: src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs [hunk 3]
```diff
@@ -221,9 +228,24 @@ private static string GetExtractorExecutable(IFileSystem fileSystem)
     /// See https://github.com/Nexus-Mods/NexusMods.App/issues/1306 for details.
     /// </remarks>
     private const bool UseSystemExtractor =
-#if USE_SYSTEM_EXTRACTOR
+#if NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR || USE_SYSTEM_EXTRACTOR
```
Comment (erri120) [inline src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:231]: There should only be one constant. Either `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR` or `USE_SYSTEM_EXTRACTOR`, not both.

**Review by erri120 — CHANGES_REQUESTED** [review]

File: src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs (hunk 3 above)
Comment (MattSturgeon) [reply src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:231]: Speaking as a downstream packager, I'm fine with these kinda changes being done in a breaking way so long as the docs get updated and the change is mentioned in release notes.

Packagers shouldn't be surprised when experimental software has breaking changes :grinning:

Comment (erri120) [reply src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:231]: There should've only been one compile constant in the beginning, which is `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR`. I still don't understand what caused #1836.

File: src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets (hunk 2 above)
Comment (Sewer56) [reply src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets:18]: The property is used below to determine if to copy the 7zz binaries to output.

File: src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs (hunk 3 above)
Comment (MattSturgeon) [reply src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:231]: > There should've only been one compile constant in the beginning, which is `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR`.

Ah yes, that's what I was using. I got confused as the diff made it look like `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR` was a new constant replacing `USE_SYSTEM_EXTRACTOR`. Should've double checked before commenting!

I don't fully understand the solution, but this seems relevant https://github.com/Nexus-Mods/NexusMods.App/pull/1919#issuecomment-2303284678:
> So we can't do an alias by appending `DefineConstants` in the `.csproj` or `.targets` file. Instead I alias by checking both define names

Comment (Sewer56) [reply src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:231]: @erri120 themselves originally added both USE_SYSTEM_EXTRACTOR and NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR.

Due to how they were used in the `.targets` file, I assumed it was meant to be an alias.
I kept this alias in the PR; should I not have done that?

AFAIK downstreams only use `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR` and not `USE_SYSTEM_EXTRACTOR`, so the latter is safe to remove.

Comment (MattSturgeon) [reply src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs]: > Setting `DefineConstants` via CLI acts as an 'absolute override', i.e. any changes you make to them, in `.csproj`, `.targets` or otherwise get discarded.

Possibly out of scope for this PR, but is that a possible justification for moving to the pattern described in https://github.com/NixOS/nixpkgs/pull/331150#discussion_r1727635149?

I.e:
```xml
  <PropertyGroup Condition="$(UseSystemExtractor) == 'true'">
    <DefineConstants>$(DefineConstants);NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR</DefineConstants>
  </PropertyGroup>
```

Paired with `dotnet build -p:UseSystemExtractor=true`.

Comment (Sewer56) [reply src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs]: Personally I would prefer it that way, after (re)discovering more of the nature in how `DefineConstants` interacts with the rest of the build system.

**Review by erri120 — APPROVED** [review]

**Comment by Sewer56** [comment]
Update: We'll be avoiding static bundling in the future; will check dependencies at runtime and emit a health check/diagnostic. For downstream's convenience, this is merged for now.
