### PR TITLE
Various Download fixes

### LINKED ISSUE #833: Spine Download Button isn't showing fancy progress version while download is in progress

### LINKED ISSUE #836: Pausing a download seems to directly cancel it (it disappears from the UI).

### LINKED ISSUE #842: Resuming a download after pausing resumes from 0%

### LINKED ISSUE #843: Resuming a download after closing App resumes from 0%

### LINKED ISSUE #844: Download throughput calculation in wrong when resuming a download

### LINKED ISSUE #845: Download Time Remaining is continues counting when downloads are paused

### LINKED ISSUE #846: Update Download Progress bar styles to match figma

### LINKED ISSUE #847: Hide progress bar and numbers when no downloads are active.

### LINKED ISSUE #848: Update download "In Progress (0)" title text and color when download status changes

### LINKED ISSUE #849: Fix missing accent colors to Text in Downloads view

### LINKED ISSUE #850: Add glow effect to Spine download button

### LINKED ISSUE #851: Make download toolbar buttons work with multi selection

### LINKED ISSUE #852: Add Resume Selected and Resume All buttons to Download view

### PR DESCRIPTION
**Pull request by Al12rs**
This PR addresses some of the issues identified from QA testing the download process:
- Pausing/Resuming issues
- Progress/Throughput incorrectness
- Multi selection for toolbar buttons
- Update UI when downloads are added/removed or their state changes
- Many styling fixes/adjustments.

In more details:
- fix #833 
- fix #836
- fix #842 
- fix #843 
- fix #844 
- fix #845 
- fix #846 
- fix #847 
- fix #848
- fix #849
- fix #850 
- fix #851
- fix #852 
- Added a couple of tests for some of the functionality fixed.
- Removed UpdateOverlay test that opened the App GitHub releases page when executed.

### CODE REVIEW

File: src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs [hunk 1]
```diff
@@ -32,15 +31,19 @@ public class NxmDownloadTask : IDownloadTask, IHaveDownloadVersion, IHaveFileSiz
     private long _defaultDownloadedSize;
 
     /// <inheritdoc />
-    public long DownloadedSizeBytes => (long)(_state.ActivityStatus?.MakeTypedReport().Current.ValueOrDefault().Value ?? (ulong)_defaultDownloadedSize);
+    public long DownloadedSizeBytes =>
+        (long)(_state.ActivityStatus?.MakeTypedReport().Current.ValueOr(() => Size.Zero).Value ??
+               (ulong)_defaultDownloadedSize);
```
Comment (erri120) [inline src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs:36]: This should be split into multiple lines for clarity.

File: src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs [hunk 2]
```diff
@@ -32,15 +31,19 @@ public class NxmDownloadTask : IDownloadTask, IHaveDownloadVersion, IHaveFileSiz
...
     /// <inheritdoc />
     public long CalculateThroughput()
     {
         if (_state.Activity == null)
             return 0;
 
-        return (long)(((ActivityReport<Size>?)_state.ActivityStatus?.GetReport())?.Throughput.Value ?? Size.Zero).Value;
+        return (long)
+            (((ActivityReport<Size>?)_state.ActivityStatus?.GetReport())?.Throughput.ValueOr(() => Size.Zero) ??
+             Size.Zero).Value;
```
Comment (erri120) [inline src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs:46]: This should be split into multiple lines for clarity.

File: src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs [hunk 3]
```diff
@@ -93,17 +96,21 @@ public async Task<Hash> DownloadAsync(IReadOnlyList<HttpRequestMessage> sources,
...
+            var activity = downloaderState.Activity as IActivitySource<Size>;
+            activity?.SetProgress(state.CompletedSize);
+            activity?.StartOrResume(state.CompletedSize);
+
 
             var writeQueue = Channel.CreateBounded<WriteOrder>(_writeQueueLength);
 
-            var fileWriter = FileWriterTask(state, writeQueue.Reader, primaryJob, cancel);
+            var fileWriter = FileWriterTask(state, writeQueue.Reader, activity!,
+                cancel);
```
Comment (erri120) [inline src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs:113]: Do a null check for `activity`.

File: src/NexusMods.Abstractions/Activities/ActivityReport.cs [hunk 4]
```diff
@@ -42,32 +42,39 @@ public class ActivityReport
     /// </summary>
     public Percent? CurrentProgress { get; init; }
 
+    /// <summary>
+    /// The current progress of the activity, if any.
+    /// </summary>
+    public Percent? StartingProgress { get; init; }
+
```
Comment (erri120) [inline src/NexusMods.Abstractions/Activities/ActivityReport.cs:49]: Should use `Optional<Percent>`.

File: src/NexusMods.Abstractions/Activities/ActivityReport.cs [hunk 5]
```diff
@@ -42,32 +42,39 @@ public class ActivityReport
...
 
     /// <summary>
-    /// The estimated total time for the activity, if any progress has been made.
+    /// The estimated remaining time for the activity, if any progress has been made.
     /// </summary>
-    public Optional<TimeSpan> EstimatedTotalTime => PercentagePerSecond.HasValue ?
-        Optional.Some(TimeSpan.FromSeconds(100 / PercentagePerSecond.Value.Value)) : Optional<TimeSpan>.None;
+    public Optional<TimeSpan> EstimatedRemainingTime => PercentagePerSecond.HasValue && CurrentProgress.HasValue
+        ? Optional.Some(TimeSpan.FromSeconds((100 - CurrentProgress.Value.Value) / PercentagePerSecond.Value.Value))
+        : Optional<TimeSpan>.None;
```
Comment (erri120) [inline src/NexusMods.Abstractions/Activities/ActivityReport.cs:63]: These should be on multiple-lines for clarity.

File: src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs [hunk 6]
```diff
@@ -1,23 +1,43 @@
...
+            {
+                Number = downloadService.GetThroughput() / Size.MB;
+                Units = "MB/s";
+                Progress = downloadService.GetTotalProgress();
+
+            }).DisposeWith(disposables);
+        });
+    }
+
+    [Reactive] public double Number { get; set; } = 4.2f;
```
Comment (erri120) [inline src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs:34]: What is this magic `4.2f` value? This isn't the designer VM.

File: src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs [hunk 7]
```diff
@@ -1,23 +1,43 @@
...
-    
-    [Reactive]
-    public ICommand Click { get; set; } = Initializers.ICommand;
-    
-    [Reactive]
-    public bool IsActive { get; set; }
+    internal const int PollTimeMilliseconds = 1000;
+
+    internal IObservable<Unit> Tick { get; } = Observable.Interval(TimeSpan.FromMilliseconds(PollTimeMilliseconds))
+        .Select(_ => Unit.Default);
```
Comment (erri120) [inline src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs:18]: These can be `private`.

File: src/NexusMods.App.UI/Overlays/Download/Cancel/CancelDownloadOverlayView.axaml.cs [hunk 8]
```diff
@@ -9,11 +9,17 @@ public partial class CancelDownloadOverlayView : ReactiveUserControl<ICancelDown
...
-            OkCancelView.Description =
+
+            OkCancelView.Description = ViewModel?.DownloadTasks.Count() == 1 ?
+                string.Format(Language.CancelDownloadOverlayView_Description_download_will_be_cancelled,
+                    ViewModel?.DownloadTasks.First().Name + " " +
+                    Language.CancelDownloadOverlayView_Description__Download) :
                 string.Format(Language.CancelDownloadOverlayView_Description_download_will_be_cancelled,
-                    ViewModel?.DownloadTask.Name);
+                    ViewModel?.DownloadTasks.Count() + " " +
+                    Language.CancelDownloadOverlayView_Description_downloads );
```
Comment (erri120) [inline src/NexusMods.App.UI/Overlays/Download/Cancel/CancelDownloadOverlayView.axaml.cs:22]: This isn't reactive? You should still use a `PopulateFromViewModel` method for consistency.

File: src/NexusMods.App.UI/Overlays/Download/Cancel/CancelDownloadOverlayViewModel.cs [hunk 9]
```diff
@@ -5,17 +5,17 @@ namespace NexusMods.App.UI.Overlays.Download.Cancel;
 
 public class CancelDownloadOverlayViewModel : AViewModel<ICancelDownloadOverlayViewModel>, ICancelDownloadOverlayViewModel
 {
-    public IDownloadTaskViewModel DownloadTask { get; } = new DownloadTaskDesignViewModel();
+    public IEnumerable<IDownloadTaskViewModel> DownloadTasks { get; } = Enumerable.Empty<IDownloadTaskViewModel>();
```
Comment (erri120) [inline src/NexusMods.App.UI/Overlays/Download/Cancel/CancelDownloadOverlayViewModel.cs:8]: Using `IEnumerable<T>` in VMs isn't ideal, since they don't have `Length`/`Count` property. I'd suggest some form of `IList<T>` like `IReadOnlyList<T>`.

File: src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs [hunk 10]
```diff
@@ -1,53 +1,263 @@
...
+                    .Select(_ => Tasks.Any(task => task.Status == DownloadTaskStatus.Paused)));
+
+            Tasks.ToObservableChangeSet()
+                .AutoRefresh(task => task.Status)
+                .Subscribe(_ =>
+                {
+                    UpdateWindowInfo();
+                    ActiveDownloadCount = Tasks.Count(task => task.Status == DownloadTaskStatus.Downloading);
+                    HasDownloads = Tasks.Any();
+                });
```
Comment (erri120) [inline src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs:200]: These need to be disposed.

File: src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs [hunk 11]
```diff
@@ -1,53 +1,263 @@
...
             // WhenActivated gets fired in wrong order and
             // parent classes need to be able to properly subscribe
             // here.
             this.RaisePropertyChanged(nameof(Tasks));
+
+            // This is necessary due to inheritance,
+            // WhenActivated gets fired in wrong order and
+            // parent classes need to be able to properly subscribe
+            // here.
+            this.RaisePropertyChanged(nameof(Columns));
```
Comment (erri120) [inline src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs:223]: We're complicated our code for no reason. This only exists so that the design VM can be fancy. Instead of inheritance, composition might be better for this.

File: src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs [hunk 12]
```diff
@@ -1,53 +1,263 @@
...
+            // Start updating on the UI thread
+            // This is a service to provide polling in case of downloaders that don't have a way of notifying
+            // changes in progress (e.g. when file name is resolved, or download progress is made).
+
+            // This is not the only mechanism, a manual refresh also can occur when tasks are added/removed.
+            var timer = new DispatcherTimer();
+            timer.Interval = TimeSpan.FromMilliseconds(PollTimeMilliseconds);
+            timer.Tick += UpdateWindowInfoEvent;
+            timer.Start();
+            Disposable.Create(timer, (tmr) => tmr.Stop()).DisposeWith(d);
```
Comment (erri120) [inline src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs:211]: Is there a benefit to using `DispatcherTimer` instead of an observable stream?

**Review by erri120 — CHANGES_REQUESTED** [review]
I've left comments on things to change.

**Comment by Al12rs** [comment]
> I've left comments on things to change.

I'm going through fixing them. Thanks for going into details, I really appreciate all the chances for improvements.

File: src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs (hunk 6 above)
Comment (Al12rs) [reply src/NexusMods.App.UI/Controls/Spine/Buttons/Download/SpineDownloadButtonViewModel.cs]: Must have been leftover from before, just a random default value. Removed.

File: src/NexusMods.App.UI/Overlays/Download/Cancel/CancelDownloadOverlayView.axaml.cs (hunk 8 above)
Comment (Al12rs) [reply src/NexusMods.App.UI/Overlays/Download/Cancel/CancelDownloadOverlayView.axaml.cs]: The number of tasks to cancel doesn't change during the life of the dialog. I updated the code to make it more standard.

File: src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs [hunk 13]
```diff
@@ -1,53 +1,263 @@
...
+    // Do nothing for now and keep disabled.
+    [Reactive] public ICommand ShowSettings { get; private set; } = ReactiveCommand.Create(() => { }, Observable.Return(false));
+
+    /// <summary>
+    /// Main constructor
+    /// </summary>
+    /// <param name="downloadService"></param>
+    /// <param name="overlayController"></param>
+    public InProgressViewModel(IDownloadService downloadService, IOverlayController overlayController)
     {
```
[the remark this answers is not in the document]
Comment (Al12rs) [reply src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs]: Used implicitly, added tag

File: src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs (hunk 12 above)
Comment (Al12rs) [reply src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs:218]: This is older code, I think from @Sewer56 . If there are no objection I'll change it to an observable stream for consistency.

File: src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs (hunk 11 above)
Comment (Al12rs) [reply src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs:230]: I think we can remove these actually. I changed the structure from 
```mermaid
classDiagram
    IInprogressViewModel <|-- InProgressCommonViewModel
    InProgressCommonViewModel <|-- InProgressViewModel
    InProgressCommonViewModel <|-- InProgressDesignViewModel
```

to
```mermaid
classDiagram
    IInprogressViewModel <|-- InProgressViewModel
    InProgressViewModel <|-- InProgressDesignViewModel
```

Comment (Al12rs) [reply src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs:230]: Before we had issues due to DesignVM chaging values of the CommonVM, thus requiring manual notifyPropertyChanged. This should no longer be an issue.

**Review by erri120 — APPROVED** [review]
