### PR TITLE
Fix archives containing invalid paths

### LINKED ISSUE #3003: Unhandled Exception when downloading or installing from drive a specific mod
# Bug Report

## Summary of Current behaviour
Attempting to download or install from disk a certain Stardew Valley mod [(FS - Wearable vanilla weapons and tools)](https://www.nexusmods.com/stardewvalley/mods/19555?tab=files&file_id=79729) using the NXM mod manager download option (initiated through either the Nexus Mod App or by searching and downloading through mod manager) results in error(s) and failure to download or install. 

### Method 1: Downloading through Nexus Mods App
Download mod [(FS - Wearable vanilla weapons and tools)](https://www.nexusmods.com/stardewvalley/mods/19555?tab=files&file_id=79729) using the NXM mod manager download option (initiated through either the Nexus Mod App or by searching and downloading through mod manager). NMA (Nexus Mods App) will display an error popup titled 'Unhandled Exception' (see errors below).  This first popup *sometimes* includes an additional description of the error, sometimes only the stacktrace is provided. Pressing 'OK' or 'X' closes the popup and the second popup appears. The second popup includes only a title ('Unhandled Exception') and a stacktrace similar to the first. Pressing the  'OK' or 'X' closes the popup and the third popup appears. Like the second error popup, the third popup includes only the same title and a similar stacktrace. Pressing 'OK' or 'X' closes the error popup window. The download button  for the mod  in the 'Actions' column in NMA (if viewing as part of a collection) becomes greyed-out in the same manner that a successfully downloaded mod does but with the text remaining as 'Download' The mod fails to download and cannot be installed.

### Method 2: Installing from drive
Download mod [(FS - Wearable vanilla weapons and tools)](https://www.nexusmods.com/stardewvalley/mods/19555?tab=files&file_id=79729) using the manual download option. Attempt to install from drive as normal. NMA (Nexus Mods App) will display an error popup titled 'Unhandled Exception' (see errors below).  Pressing 'OK' or 'X' closes the popup and the second popup appears. The second popup includes only a title ('Unhandled Exception') and a stacktrace similar to the first. Pressing 'OK' or 'X' closes the popup. The mod fails to be installed. 

## What is the expected behaviour?
Attempting to download a mod hosted on the Nexus Mods site through the NMA should result in the mod properly being downloaded without error.

Attempting to install a mod downloaded from the Nexus Mods site should properly install (either through simple installation or through advanced installation) provided that the mod is for the appropriate game.

##### Error 1a
**Title**: Unhandled Exception
**Description Text** (not always present): Exception while running handler NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler for \`nxm://stardewvalley/mods/19555/files/79729?key=iXxGLaKaFdUPhgEvW6zeJQ&expires=1744258762&user_id=XXXXXXXX\`

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/4b889b4e-f252-4283-8368-92b41b574463/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at NexusMods.Paths.FileSystem.InternalOpenFile(AbsolutePath path, FileMode mode, FileAccess access, FileShare share)
   at NexusMods.Paths.AbsolutePath.Read()
   at NexusMods.Hashing.xxHash3.Paths.AbsolutePathExtensions.XxHash3Async(AbsolutePath path, Nullable`1 token, Func`2 reportFn)
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 67
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 98
   at NexusMods.Library.AddLibraryFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 59
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.Library.AddDownloadJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddDownloadJob.cs:line 38
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleModUrl(CancellationToken cancel, NXMModUrl modUrl) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 178
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleModUrl(CancellationToken cancel, NXMModUrl modUrl) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 178
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.Handle(String url, CancellationToken cancel) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 81
   at NexusMods.SingleProcess.CommandLineConfigurator.RunLink(String[] args, CancellationToken cancellationToken) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.SingleProcess/CommandLineConfigurator.cs:line 160
``` 
##### Error 2a
**Title**: Unhandled Exception
```
System.AggregateException: One or more errors occurred. (Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/4b889b4e-f252-4283-8368-92b41b574463/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/4b889b4e-f252-4283-8368-92b41b574463/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at NexusMods.Paths.FileSystem.InternalOpenFile(AbsolutePath path, FileMode mode, FileAccess access, FileShare share)
   at NexusMods.Paths.AbsolutePath.Read()
   at NexusMods.Hashing.xxHash3.Paths.AbsolutePathExtensions.XxHash3Async(AbsolutePath path, Nullable`1 token, Func`2 reportFn)
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 67
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 98
   at NexusMods.Library.AddLibraryFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 59
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.Library.AddDownloadJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddDownloadJob.cs:line 38
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleModUrl(CancellationToken cancel, NXMModUrl modUrl) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 178
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleModUrl(CancellationToken cancel, NXMModUrl modUrl) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 178
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.Handle(String url, CancellationToken cancel) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 81
   at NexusMods.SingleProcess.CommandLineConfigurator.RunLink(String[] args, CancellationToken cancellationToken) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.SingleProcess/CommandLineConfigurator.cs:line 160
   --- End of inner exception stack trace ---
``` 
##### Error 3a
**Title**: Unhandled Exception 
```
System.AggregateException: One or more errors occurred. (Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/4b889b4e-f252-4283-8368-92b41b574463/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/4b889b4e-f252-4283-8368-92b41b574463/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at NexusMods.Paths.FileSystem.InternalOpenFile(AbsolutePath path, FileMode mode, FileAccess access, FileShare share)
   at NexusMods.Paths.AbsolutePath.Read()
   at NexusMods.Hashing.xxHash3.Paths.AbsolutePathExtensions.XxHash3Async(AbsolutePath path, Nullable`1 token, Func`2 reportFn)
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 67
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 98
   at NexusMods.Library.AddLibraryFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 59
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.Library.AddDownloadJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddDownloadJob.cs:line 38
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleModUrl(CancellationToken cancel, NXMModUrl modUrl) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 178
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.HandleModUrl(CancellationToken cancel, NXMModUrl modUrl) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 178
   at NexusMods.CLI.Types.IpcHandlers.NxmIpcProtocolHandler.Handle(String url, CancellationToken cancel) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.Cli/Types/IpcHandlers/NxmIpcProtocolHandler.cs:line 81
   at NexusMods.SingleProcess.CommandLineConfigurator.RunLink(String[] args, CancellationToken cancellationToken) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.SingleProcess/CommandLineConfigurator.cs:line 160
   --- End of inner exception stack trace ---
```

##### Error 1b
**Title:** Unhandled Exception
```
System.AggregateException: One or more errors occurred. (Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/048c723a-a079-4b69-a6ad-e1cd71c2efe0/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/048c723a-a079-4b69-a6ad-e1cd71c2efe0/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at NexusMods.Hashing.xxHash3.Paths.AbsolutePathExtensions.XxHash3Async(AbsolutePath path, Nullable`1 token, Func`2 reportFn)
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 67
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 98
   at NexusMods.Library.AddLibraryFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 59
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.Library.AddLocalFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLocalFileJob.cs:line 31
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.App.UI.Pages.LibraryPage.LibraryViewModel.<>c__DisplayClass55_0.<<AddFilesFromDisk>b__3>d.MoveNext() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs:line 350
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__49`1.<<ForAsync>b__49_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NexusMods.App.UI.Pages.LibraryPage.LibraryViewModel.AddFilesFromDisk(IStorageProvider storageProvider, CancellationToken cancellationToken) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs:line 344
   at R3.ReactiveCommandExtensions.<>c__DisplayClass5_0`1.<<ToReactiveCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at R3.AwaitOperationParallelObserver`1.StartAsync(T value)
   --- End of inner exception stack trace ---
``` 
##### Error 2b
**Title**: Unhandled Exception
```
System.AggregateException: One or more errors occurred. (Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/048c723a-a079-4b69-a6ad-e1cd71c2efe0/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/me/.local/state/NexusMods.App/Temp/048c723a-a079-4b69-a6ad-e1cd71c2efe0/[FS] Stardew Vanilla Weaponry/Accessories/LeatherScabbard_l/accessory.png'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at NexusMods.Hashing.xxHash3.Paths.AbsolutePathExtensions.XxHash3Async(AbsolutePath path, Nullable`1 token, Func`2 reportFn)
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 67
   at NexusMods.Library.AddLibraryFileJob.AnalyzeFile(IJobContext`1 context, AbsolutePath filePath, Boolean isNestedFile) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 98
   at NexusMods.Library.AddLibraryFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLibraryFileJob.cs:line 59
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.Library.AddLocalFileJob.StartAsync(IJobContext`1 context) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Library/AddLocalFileJob.cs:line 31
   at NexusMods.Jobs.JobContext`2.Start() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.Jobs/JobContext.cs:line 42
   at NexusMods.App.UI.Pages.LibraryPage.LibraryViewModel.<>c__DisplayClass55_0.<<AddFilesFromDisk>b__3>d.MoveNext() in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs:line 350
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__49`1.<<ForAsync>b__49_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NexusMods.App.UI.Pages.LibraryPage.LibraryViewModel.AddFilesFromDisk(IStorageProvider storageProvider, CancellationToken cancellationToken) in /home/me/.cache/yay/nexusmods-app-git/src/nexusmods-app/src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs:line 344
   at R3.ReactiveCommandExtensions.<>c__DisplayClass5_0`1.<<ToReactiveCommand>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at R3.AwaitOperationParallelObserver`1.StartAsync(T value)
   --- End of inner exception stack trace ---
``` 
### Logs
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/19642558/nexusmods.app.main.current.log)

[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/19642560/nexusmods.app.slim.current.log)

### Other
The errors seem to be pointing to a failure to find one of the mods asset files. I do not know why this issues is being thrown for attempting to download the mod, but I can verify that when downloading the mod manually that the listed 'missing' file is indeed present, appears to have no issues or corruption, and all JSON data files associated with the file in question _**appear**_ to have no errors and have parity with the JSON data files of other asset files which do not throw the same exception.

One thing of note is that under the mod's posts on the Nexus Mods site is the following comment:
```04 May 2024, 4:22PM
[Fashion Sense] Content pack FS - Stardew Valley Vanilla Weaponry and gear is missing a accessory.json under LeatherScabbard_l getting this warning?```
The user mentions getting a warning attempting to use the mod. Interestingly, the error points to the same asset but with the corresponding JSON file of the asset file which appears to be triggering this bug report's error being missing instead of the asset file itself.

This makes me think there is some fort of error regarding one of the JSON files in this mod. However, I do not know why this would be causing issues with downloading or installing the mod.

### Operating system:
- Windows 10 [ ]
- Windows 11 [ ]
- Linux [x]
```
me@archlinux 
------------ 
OS: Arch Linux x86_64 
Kernel: 6.12.16-1-lts 
Uptime: 1 hour, 5 mins 
Packages: 1972 (pacman) 
Shell: bash 5.2.37 
Resolution: 1920x1080 
DE: Plasma 
WM: kwin 
Theme: Breeze Dark [Plasma] 
Icons: candy-icons [Plasma], candy-icons [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 6406MiB / 48103MiB 

```

### App version: Stardew Valley Preview 6446.0.0.0

### NexusMods account type:
- Premium [ ]
- Free [x]

### QA Checklist:
- [ ] Add QA label if relevant
- [x] Add repro steps
- [x] Add expected behaviour
- [ ] Add known limitations with the fix or issues
- [ ] QA test Windows
- [ ] QA test Linux

### PR DESCRIPTION
**Pull request by erri120**
Fixes #3003.

Fixes extraction of invalid paths on Windows and Unix.

### CODE REVIEW

**Review by Sewer56 — COMMENTED** [review]
I have my doubts on whether this is the correct approach to take here.

Ideally, downloaded mods are as immutable as possible; we should change them the least we can. This includes file names, file paths and anything that comes to mind.

So what it boils down to; somewhere behind the scenes, our App is trimming whitespace. Be it in a sanitise step in the paths library, or in some similar place. What this PR does is trim whitespace at the extract step. This is in order to match what the analysis part of the App is expecting down the road when downloading/sourcing a mod. And this now happens, irrespective of who the caller of the File Extractor API is.

I can think of a few edge cases here:

- Callers to file extractor which are not fed into the Analysis steps.
    - They may expect a certain file path inside, which may no longer match.
    - But this would probably be trivial to fix on our end, thankfully.
- Mods with manifests, that can specify paths to files within the package may break.
    - For example, image a FOMOD which specified `<image path="images /option_a.png"/>`.
    - Removing whitespace at extract step has now broken this part of the schema/manifest.

My concern lies particularly with the latter; I worry that mutating mods at the extract step will have longer term ratifications that will require further fixes all throughout different parts of the App.

Instead, I think we should be preserving paths in this scenario, rather than mutating them forcibly on disk.

@Al12rs thoughts?

**Comment by erri120** [comment]
Here's the fun part: this is already broken even if we don't trim whitespaces.

Apparently, on Windows 7z will extract `foo ` as `foo_` as seen in the recent test failure:

```
bar/foo_/bar.txt
```

**Comment by Sewer56** [comment]
> Apparently, on Windows 7z will extract foo  as foo_ as seen in the recent test failure:

Goddamn it.

**Comment by Sewer56** [comment]
Given how rare whitespace is, and how common 7z is, I guess it might be fine.
I'll just wait for others' thoughts.

**Comment by erri120** [comment]
From the Windows docs https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

**Review by Sewer56 — APPROVED** [review]

**Comment by Al12rs** [comment]
I downloaded the archive on windows and 7z Gui shows the trailing space. 

Using the default explorer shell option to extract the archive on windows 11, extracted folder didn't have the trailing whitespace.

Using another tool (Extract Now) the folder was extracted with the trailing space.

Windows then seems to choke on the path when attempting to delete it and it had to be force deleted with:
`rd /s /q "G:\Documents\Downlaods\zip-with-spaces"`  

As from explorer or from powershell it was impossible.

File: src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs [hunk 1]
```diff
@@ -21,185 +24,320 @@ namespace NexusMods.FileExtractor.Extractors;
...
-                throw new Exception("While executing 7zip");
+            output[outputIndex++] = current;
         }
-        catch (CommandExecutionException ex)
+
+        var slice = output.SliceFast(start: 0, length: outputIndex);
+        slice.Reverse();
+
+        return slice.ToString();
+    }
```
Comment (Al12rs) [inline src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs]: I would just use Trim instead to keep the code simple:
```
    internal static string FixFileName(ReadOnlySpan<char> input)
    {
        return input.TrimEnd(" .").ToString();
    }
```

**Review by Al12rs — APPROVED** [review]
