### PR TITLE
Resilient game locators and heroic fix

### LINKED ISSUE #2129: HeroicGOGHandler crashes app
Erroneous issue, I believe it (may) be a gamefinder bug

### PR DESCRIPTION
**Pull request by erri120**
Fixes #2129.

### CODE REVIEW

File: src/NexusMods.DataModel/GameRegistry/GameRegistry.cs [hunk 1]
```diff
@@ -133,14 +145,29 @@ private async IAsyncEnumerable<GameInstallation> FindInstallations()
...
+
+                    try
+                    {
+                        if (!enumerator.MoveNext()) break;
+                        var result = enumerator.Current;
+                        value = Register(game, result, locator);
+                    }
+                    catch (Exception e)
+                    {
+                        _logger.LogError(e, "Exception in loator");
```
Comment (Sewer56) [inline src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:161]: Typo here

**Review by Sewer56 — APPROVED** [review]

File: src/NexusMods.DataModel/GameRegistry/GameRegistry.cs (hunk 1 above)
Comment (erri120) [inline src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:161]:
```suggestion
                        _logger.LogError(e, "Exception in locator");
```
