### PR TITLE
Pass sync tree directly to the diagnostic emitter

### LINKED ISSUE #3682: Cannot acccess file being used by another process
Happens most commonly for `Cyberpunk 2077\tools\redmod\bin\REDmodLog.txt`, exception gets thrown from the `UndeployableLoadoutDueToMissingGameFiles` diagnostic emitter which re-indexes the game folder. Would likely be fixed by #2806 and #3621 to pass the sync tree directly to the emitter.

```
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.<>c__DisplayClass44_0.<<ReindexState>b__0>d.MoveNext() in /_/src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 1336
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.ReindexState(GameInstallation installation, Boolean ignoreModifiedDates, IConnection connection, ITransaction tx) in /_/src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 1280
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.ReindexState(GameInstallation installation, Boolean ignoreModifiedDates, IConnection connection) in /_/src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 1227
   at NexusMods.Abstractions.Loadouts.Synchronizers.ALoadoutSynchronizer.BuildSyncTree(ReadOnly loadout) in /_/src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs:line 359
   at NexusMods.Games.FileHashes.Emitters.UndeployableLoadoutDueToMissingGameFiles.Diagnose(ReadOnly loadout, CancellationToken cancellationToken)+MoveNext() in /_/src/NexusMods.Games.FileHashes/Emitters/UndeployableLoadoutDueToMissingGameFiles.cs:line 17
   at NexusMods.DataModel.Diagnostics.DiagnosticManager.<>c__DisplayClass8_0.<<GetLoadoutDiagnostics>b__0>d.MoveNext() in /_/src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs:line 92
--- End of stack trace from previous location ---
   at NexusMods.DataModel.Diagnostics.DiagnosticManager.<>c__DisplayClass8_0.<<GetLoadoutDiagnostics>b__0>d.MoveNext() in /_/src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs:line 92
```

### PR DESCRIPTION
**Pull request by erri120**
Fixes #3682 (hopefully).

### CODE REVIEW

File: src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs [hunk 1]
```diff
@@ -80,7 +80,9 @@ private async Task<Diagnostic[]> GetLoadoutDiagnostics(Loadout.ReadOnly loadout,
     {
         var diagnosticEmitters = loadout.InstallationInstance.GetGame().DiagnosticEmitters;
         var synchronizer = loadout.InstallationInstance.GetGame().Synchronizer;
-        var syncTree = (await synchronizer.BuildSyncTree(loadout)).ToFrozenDictionary();
+        var baseSyncTree = await synchronizer.BuildSyncTree(loadout);
+        synchronizer.ProcessSyncTree(baseSyncTree);
```
Comment (Al12rs) [inline src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs:84]: This adds signature and actions to the tree, is that info needed?

**Review by Al12rs — APPROVED** [review]
