### PR TITLE
Apply fixes and refinements

### LINKED ISSUE #983: Outside changes are discarded on ingest (new loadout isn't used)
Currently we create a new `Loadout` when ingesting outside changes, but that loadout is never used:
- [ ] `Loadout` with ingested changes isn't set to be the latest revision for its `LoadoutId`
- [ ] During Ingest as Part of Apply operation, the original loadout is applied instead of the one containing the merged ingested changes.

## Notes:
After discussing with Design, the default desired way for integrating outside changes should be:
- Branch at the last applied loadout revision
- Merge outside changes on top of that old revision
- Rebase any Unapplied changes in the loadout that came after that revision on top

See #987 for details

### LINKED ISSUE #984: `DiskState` is stored with loadout revision id that is not guaranteed to match the state
### Description:
Every time a Loadout is Applied to disk, we store a snapshot of the state of the disk `DiskState` at that moment.
The disk state also contains the Loadout Revision Id that was applied on disk, used to know what was the last applied Loadout and revision.

### Problem:
Currently the flattened loadout of the revision saved is not guaranteed to actually match the `DiskState`.
This can happen when trying to Apply and outside changes need to first be ingested.

Currently the outside changes are merged on top of the latest revision of the loadout, meaning that that revision will contain both the outside changes and the yet to be applied changes. The yet to be applied changes are not actually on disk at this point, meaning that the flattened loadout tree and the disk tree don't actually match.

### Solution:
The outside changes should be merged on top of the Last Applied Revision, not on top of the latest unapplied revision.
This will crate a new loadout that should match the current disk state. That revision can be store with the disk state.

The merged revision can then be either merged with the latest unapplied changes, or the unapplied changes can be rebased on top of the new merged revision.
Rebasing should be the default solution after discussing this with Desing.

### LINKED ISSUE #986: Use unique key to identify a `GameInstallation` in the DataStore
Currently we identify the GameInstallation as `GameName+version+Store` which breaks on game update.
We need this as a Key to store the last known `DiskState` of a particular GameInstallation folder(s)

Store+StoreID should be enough
E.g. `Steam+489830` for SkyrimSpecial edition
This should be enough to uniquely identify a game install folder, because for each game you can only have one install in a store.

Alternative, add a guid for each supported game and attach that to the store.

### LINKED ISSUE #987: Ingest outside changes into last applied loadout instead of current one
When during an Apply operation, some outside changes are detected, these are currently ingested into the loadout that we plan to Apply.
We should instead ingest the detected outside changes into the last loadout that was applied to disk, as the changes were done on the `DiskState` representing that loadout revision.

Ingesting changes should create a new loadout revision that has the last applied loadout revision as the parent.
The outside changes should not be ingested on top of the newest unapplied revision, of that loadout, since those changes were not on disk, Those unapplied changes should be rebased on top of the ingested changes.

### PR DESCRIPTION
**Pull request by Al12rs**
- fixes #986
- fixes #987
- fixes #984
- fixes #983
- Handles parts of #995

### Recap:
- Apply button now correctly shows up when current loadout revision != last applied revision
- Apply button now shows Activate text when you need to switch loadouts
- Apply button now ingests outside changes and merges uncommitted changes on top
- Launch button no longer applies, but still merges at the end of the run
- Last applied revision is now correctly saved and restored
- Bunch of Apply button styling fixes and improvements

## Warning!
This requires nuking the Datamodel. App will crash and burn otherwise as its missing lastAppliedRevision

### CODE REVIEW

**Review by halgari — APPROVED** [review]

File: src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs [hunk 1]
```diff
@@ -67,6 +76,22 @@ private IId MakeId(GameInstallation installation)
         if (data == null) return null;
         using var ms = new MemoryStream(data);
         using var compressed = new GZipStream(ms, CompressionMode.Decompress);
-        return JsonSerializer.Deserialize<DiskStateTree>(compressed);
+        return JsonSerializer.Deserialize<DiskStateTree>(compressed, _jsonSerializerOptions);
+    }
+
+    /// <Inheritdoc />
+    public IId? GetLastAppliedLoadout(GameInstallation gameInstallation)
```
Comment (erri120) [inline src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs:83]: `inheritdoc` instead of `Inheritdoc`.

File: src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs [hunk 2]
```diff
@@ -20,16 +20,21 @@ public class DiskStateRegistry : IDiskStateRegistry
 {
     private readonly ILogger<DiskStateRegistry> _logger;
     private readonly IDataStore _dataStore;
+    private readonly IDictionary<GameInstallation, IId> _lastAppliedRevisionDictionary = new Dictionary<GameInstallation, IId>();
+    private readonly Subject<(GameInstallation gameInstallation, IId loadoutRevision)> _lastAppliedRevisionSubject = new();
```
Comment (erri120) [inline src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs:24]: This can be simplified using a `SourceCache`.

File: src/NexusMods.DataModel/ApplyService.cs [hunk 3]
```diff
@@ -12,14 +15,19 @@ public class ApplyService : IApplyService
...
     /// DI Constructor
     /// </summary>
-    public ApplyService(ILoadoutRegistry loadoutRegistry, ILogger<ApplyService> logger)
+    public ApplyService(ILoadoutRegistry loadoutRegistry, IDiskStateRegistry diskStateRegistry, ILogger<ApplyService> logger)
     {
         _loadoutRegistry = loadoutRegistry;
         _logger = logger;
+        _diskStateRegistry = diskStateRegistry;
+
+        _lastAppliedRevisionObservable = _diskStateRegistry.LastAppliedRevisionObservable;
```
Comment (erri120) [inline src/NexusMods.DataModel/ApplyService.cs:30]: `ApplyService` shouldn't have the observable property from `IDiskStateRegistry` as a private field.

File: src/NexusMods.DataModel/ApplyService.cs [hunk 4]
```diff
@@ -32,29 +40,104 @@ public async Task<Loadout> Apply(LoadoutId loadoutId)
...
+    public async Task<Loadout> Ingest(GameInstallation gameInstallation)
+    {
+        var lastAppliedRevision = GetLastAppliedLoadout(gameInstallation);
+        if (lastAppliedRevision is null)
+        {
+            throw new InvalidOperationException("Game installation does not have a last applied loadout to ingest into");
+        }
+
+        var lastLoadout = _loadoutRegistry.GetLoadout(lastAppliedRevision);
+        var lastAppliedLoadout = lastLoadout ?? throw new Exception("Loadout not found for last applied revision");
```
Comment (erri120) [inline src/NexusMods.DataModel/ApplyService.cs:100]: Don't throw an exception of type `Exception`. Try to find an exception type that has more meaning or create a custom `Exception` class.

File: src/NexusMods.DataModel/ApplyService.cs [hunk 5]
```diff
@@ -32,29 +40,104 @@ public async Task<Loadout> Apply(LoadoutId loadoutId)
...
+        
+        var loadoutWithIngest = await lastAppliedLoadout.Ingest();
+        
+        // Get the latest loadout revision
+        var latestRevision = _loadoutRegistry.Get(loadoutWithIngest.LoadoutId);
+        if (latestRevision is null)
+            throw new Exception("No latest revision found for last applied loadout");
```
Comment (erri120) [inline src/NexusMods.DataModel/ApplyService.cs:107]: Don't throw an exception of type `Exception`. Try to find an exception type that has more meaning or create a custom `Exception` class.

File: src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs (hunk 2 above)
Comment (Al12rs) [reply src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs:24]: Not as easily as I would like since the revision Id doesn't have a gameInstallation field and getting it from the revision id requires going through the LoaodutRegistry. 
Considering that I don't think it's worth it for now. Current code is pretty simple for now.
I'll keep it in mind though if code gets more complex later

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs [hunk 6]
```diff
@@ -40,56 +49,72 @@ public ApplyControlViewModel(LoadoutId loadoutId, IServiceProvider serviceProvid
...
         {
+            _loadoutRegistry.RevisionsAsLoadouts(loadoutId)
+                .OnUI()
+                .BindToVM(this, vm => vm.NewestLoadout)
+                .DisposeWith(disposables);
+
+            _applyService.LastAppliedRevisionFor(_gameInstallation)
+                .OnUI()
+                .BindToVM(this, vm => vm.LastAppliedRevisionId)
+                .DisposeWith(disposables);
```
Comment (erri120) [inline src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:74]: Use [OAPH](https://github.com/Nexus-Mods/NexusMods.App/blob/main/docs/development-guidelines/UICodingGuidelines.md#viewmodel-properties) instead of `BindToVM` to expose these two properties.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs [hunk 7]
```diff
@@ -40,56 +49,72 @@ public ApplyControlViewModel(LoadoutId loadoutId, IServiceProvider serviceProvid
...
+                .Select(revId =>
+                {
+                    var loadout = _loadoutRegistry.GetLoadout(revId);
+                    if (loadout is null)
+                        throw new ArgumentException("Loadout not found for revision: " + revId);
+                    return loadout.LoadoutId;
+                })
+                .OnUI()
+                .BindToVM(this, vm => vm.LastAppliedLoadoutId)
+                .DisposeWith(disposables);
```
Comment (erri120) [inline src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:86]: `LastAppliedLoadoutId` is set by two different observable streams, you should merge these two streams into one.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs [hunk 8]
```diff
@@ -16,19 +18,26 @@ public class ApplyControlViewModel : AViewModel<IApplyControlViewModel>, IApplyC
 
     private readonly LoadoutId _loadoutId;
     private readonly GameInstallation _gameInstallation;
-    private LoadoutId _lastAppliedLoadoutId;
-    private IId _lastAppliedRevisionId;
-    private readonly ObservableAsPropertyHelper<Abstractions.Loadouts.Loadout> _newestLoadout;
+    private readonly string _activateLoadoutText = Language.ApplyControlViewModel__ACTIVATE_LOADOUT;
+    private readonly string _activateAndApplyText = Language.ApplyControlViewModel__ACTIVATE_AND_APPLY;
+    private readonly string _applyText = Language.ApplyControlViewModel__APPLY;
```
Comment (erri120) [inline src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:23]: These should be removed. Use `Language` directly.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs (hunk 6 above)
Comment (Al12rs) [reply src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:74]: I didn't use OAPH deliberately here to ensure that the update would happen immediately:

> It is important to note that OAPH will not set the property value immediately, but will rather schedule it on the provided or default scheduler. The [Reactive] property with .BindTo() should be used for business-critical code.

Second paragraph here:
https://www.reactiveui.net/docs/handbook/observable-as-property-helper

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs (hunk 7 above)
Comment (Al12rs) [reply src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:86]: One is last applied `RevisionId`, one is last applied `LoadoutId`

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs (hunk 6 above)
Comment (erri120) [reply src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:74]: And from our own coding guidelines:

> Always use ObservableAsPropertyHelper<T> (OAPH) to expose the latest values from an IObservable<T> that is async or runs on the task pool scheduler. The OAPH is scheduled by default meaning it doesn't set the value immediately.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs (hunk 7 above)
Comment (erri120) [reply src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:86]: Ah nvm.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs [hunk 9]
```diff
@@ -40,56 +49,70 @@ public ApplyControlViewModel(LoadoutId loadoutId, IServiceProvider serviceProvid
...
-
-        (_lastAppliedLoadoutId, _lastAppliedRevisionId) = GetLastAppliedLoadout();
-
-        _newestLoadout = _loadoutRegistry.RevisionsAsLoadouts(loadoutId)
-            .ToProperty(this, vm => vm.NewestLoadout, scheduler: RxApp.MainThreadScheduler);
+        _gameInstallation = currentLoadout.Installation;
         
+        _lastAppliedRevisionId =_applyService.LastAppliedRevisionFor(_gameInstallation)
+            .OnUI()
+            .ToProperty(this, vm => vm.LastAppliedRevisionId);
```
Comment (erri120) [inline src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:66]: Set the scheduler in `ToProperty` to `RxApp.MainThreadScheduler` and remove the `OnUI` call.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs [hunk 10]
```diff
@@ -40,56 +49,70 @@ public ApplyControlViewModel(LoadoutId loadoutId, IServiceProvider serviceProvid
...
+                    .Select(revId =>
+                        {
+                            var loadout = _loadoutRegistry.GetLoadout(revId);
+                            if (loadout is null)
+                                throw new ArgumentException("Loadout not found for revision: " + revId);
+                            return loadout.LoadoutId;
+                        }
+                    )
+                    .OnUI()
+                    .BindToVM(this, vm => vm.LastAppliedLoadoutId)
```
Comment (erri120) [inline src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:82]: Unnecessary `OnUI` call.

File: src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs [hunk 11]
```diff
@@ -40,56 +49,70 @@ public ApplyControlViewModel(LoadoutId loadoutId, IServiceProvider serviceProvid
...
+                _applyReactiveCommand.IsExecuting
+                    .Subscribe(isExecuting => IsApplying = isExecuting)
+                    .DisposeWith(disposables);
+
+                this.WhenAnyValue(vm => vm.LastAppliedLoadoutId,
+                        vm => vm.NewestLoadout
+                    )
+                    .Select(_ => !LastAppliedLoadoutId.Equals(_loadoutId) ? Language.ApplyControlViewModel__ACTIVATE_AND_APPLY : Language.ApplyControlViewModel__APPLY)
+                    .OnUI()
+                    .BindToVM(this, vm => vm.ApplyButtonText)
```
Comment (erri120) [inline src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs:107]: Unnecessary `OnUI` call.
