### PR TITLE
Fix Active loadout state bug

### LINKED ISSUE #2563: Last Applied Loadout status is bugged when switching loadouts
Image

## Summary
After switching between two empty loadouts, they both appear to be the Active loadouts.

## Steps to reproduce
Switch between two empty loadouts.

## What is the expected behaviour?
The old loadout should not longer show up as the last applied one, only the new one should

## Other information:
Bug appears to be in `SynchronizerService.StatusForLoadout()`. 
Early guess is that a long Diff operation is triggered, the status is changed, then the diff operation finishes, and the result overrides the previously set result.

### PR DESCRIPTION
**Pull request by Al12rs**
- Fixes #2563

Fix incorrect LastApplied states being returned due to long diff operation returning out of order.
Using R3 we can ensure that the async operations are executed sequentially, and longer operations don't override later results.

### CODE REVIEW

File: src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs [hunk 1]
```diff
@@ -170,49 +170,51 @@ private IObservable<LoadoutSynchronizerState> CreateStatusObservable(LoadoutId l
...
-        var statusObservable = Observable.CombineLatest(isBusy,
-                lastApplied,
+        var statusObservable = isBusy.CombineLatest(lastApplied,
                 revisions,
                 (busy, last, rev) => (busy, last, rev.loadout, rev.revDbTx)
             )
             .DistinctUntilChanged()
-            .SelectMany(
-                async tuple =>
+            .ToObservable()
```
Comment (erri120) [inline src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs:180]: Should try and keep as much of the observable stream in R3. I'd suggest moving this further up.

File: src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs [hunk 2]
```diff
@@ -170,49 +170,51 @@ private IObservable<LoadoutSynchronizerState> CreateStatusObservable(LoadoutId l
...
                     return diffFound ? LoadoutSynchronizerState.NeedsSync : LoadoutSynchronizerState.Current;
-                }
+                },
+                awaitOperation: AwaitOperation.Sequential
             )
             .Replay(1)
             .RefCount();
 
-        return statusObservable;
+        return statusObservable.AsSystemObservable();
```
Comment (erri120) [inline src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs:217]: At this point we should return an R3 observable.

File: src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs (hunk 1 above)
Comment (Al12rs) [reply src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs:180]: I changed most of the code in the function and called to be R3. I didn't change the interface signature as that would have required changing all the users and I didn't want to go too out of scope

**Review by erri120 — APPROVED** [review]

File: src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs [hunk 3]
```diff
@@ -145,69 +145,71 @@ public async Task<IObservable<LoadoutSynchronizerState>> StatusForLoadout(Loadou
...
+                            var diffTree = GetApplyDiffTree(loadoutId);
+                            var diffFound = diffTree.GetAllDescendentFiles().Any(f => f.Item.Value.ChangeType != FileChangeType.None);
+                            _logger.LogTrace("Changes found in loadout {LoadoutId}: {DiffFound}", loadoutId, diffFound);
+                            return diffFound;
+                        }, cancellationToken);
 
                     return diffFound ? LoadoutSynchronizerState.NeedsSync : LoadoutSynchronizerState.Current;
-                }
+                },
+                awaitOperation: AwaitOperation.Sequential
```
Comment (erri120) [inline src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs:212]: Should be `Switch`.

**Review by erri120 — CHANGES_REQUESTED** [review]

**Review by erri120 — APPROVED** [review]
